<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="coco.names">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="CopyNativeDll" AfterTargets="Build">
    <PropertyGroup>
      <NativeDll>$(MSBuildProjectDirectory)\..\artifacts\native\$(Configuration)\YoloDeploy.Native.dll</NativeDll>
    </PropertyGroup>
    <Copy SourceFiles="$(NativeDll)"
          DestinationFolder="$(OutDir)"
          Condition="Exists('$(NativeDll)')" />
  </Target>
</Project>
